# Generated by Django 2.0.2 on 2018-07-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='ZOz0tbETATYstw3hpyBN628znPp5PA5c', max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
